<?php

namespace AppBundle\Repository;
/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOrderByDate($min){
        $database = $this->getEntityManager();
        $query = $database->createQuery(
            'SELECT a
            FROM AppBundle:Article a
            WHERE a.vote > :min
            ORDER BY a.vote'
        )->setParameter('min', $min);
        return $article = $query->getArrayResult();
    }
}
