<?php

namespace AppBundle\Repository;

/**
 * CommuneFranceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommuneFranceRepository extends \Doctrine\ORM\EntityRepository
{
}
