<?php

namespace AppBundle\Repository;

/**
 * NewEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
